#!/usr/bin/env bash

export TEMPLATE_ELASTIC_VERSION="6.8.1"
export TEMPLATE_ELASTIC_STATSD_VERSION="${TEMPLATE_ELASTIC_VERSION}.0"
export TEMPLATE_SUPPORT_DIAGNOSTICS_VERSION="6.4.4"
export TEMPLATE_DCOS_SDK_VERSION="0.40.5-1.3.4"